### ISSUE TITLE
Windows variables ignored

### ISSUE THREAD

**Issue by bsahm12** [rubrikinc/rbkcli#16]
**Expected Behavior**
Setting Windows variables 'rubrik_cdm_node_ip' and 'rubrik_cdm_token' would enable authentication for rbkcli commands

**Current Behavior**
The above variables appear to be ignored. Running a rbkcli command still requests the IP, username, and password to be entered

**Failure Information**
_C:>rbkcli help
Rubrik server IP:_

_C:> set
...rubrik_cdm_node_ip=172.24.17.16
rubrik_cdm_token=eyJ0eXAiOiJKV1Q_

These variables are also in the Environment Variables
**Steps to Reproduce**

See Failure Info above

**Context**

Running on Windows Server 2016 Datacenter (64 bit), in CMD window
Python 3.7.3
retrieved rbkcli via pip

**Failure Logs**

None

* Use verbose outputs to capture any debug information.
* Paste into a code block. -->

**Comment by Bmanesco** [comment]
Hey @bsahm12,  
Thank you for reporting this! I did some investigation and noticed that the real bug  here is: 
- *rbkcli* requires all environmental variables to be exported, in order to work, but it does not require all of them to be valid. 

Therefore by doing the following it will work (as a workaround), untill I fix the logic for the required Environmental variables:
`
set rubrik_cdm_node_ip=<IP>
set rubrik_cdm_username=""
set rubrik_cdm_password=""
set rubrik_cdm_token=<token>
`
Once you provide the token it will ignore the value provided in username and password, so it won't try to authenticate with them, it will successfully authenticate with token. And there is the bug, even though the value is null, the variable needs to be provided. 

Please try that out and let me know how it goes.

Thank you!

**Comment by Bmanesco** [comment]
Closing this issues, let me know if you have any other questions.

**Comment by bsahm12** [comment]
Sorry, I haven't had a chance to test this out. Once I do, I'll let you
know; your description makes sense. Thanks!

  - Bill

**Comment by bsahm12** [comment]
Finally got around to testing this, and it still fails from what I can tell. 

Variables:
rubrik_cdm_node_ip=172.24.17.16
rubrik_cdm_password=""
rubrik_cdm_token=eyJ0eXAiO...
rubrik_cmd_username=""

Command:
C:\Users\bill.sahm>rbkcli cluster me
Rubrik server IP:

**Comment by Bmanesco** [comment]
Hello @bsahm12, 

   Thanks for answering, can you please run the following command on your CMD:

```
>set | find "rubrik"
```

  If your variables are set correctly you should see the following:

```
>set | find "rubrik"
rubrik_cdm_node_ip="<IP>"
rubrik_cdm_password=""
rubrik_cdm_token="<token>"
rubrik_cdm_username=""
```

  If one of the variables is missing or set with the wrong name (such as cmd instead of cdm), rbkcli will not load any of them as they might be inconsistent. 

  In case you are still having the issue after re-exporting the correct variables can you please check the KB:
https://github.com/rubrikinc/rbkcli/blob/devel/docs/KB0019.md

  This should give you an idea if there is any issues with your environment, meaning if it is not in the expected versions.

  Please let me know if you have any questions.

Thank you!
