### ISSUE TITLE
API Token is not recognized

### ISSUE THREAD

**Issue by keilma** [rubrikinc/rbkcli#7]
**Expected Behavior**
When an API token is set it should be used for authentication

**Current Behavior**
Under Windows the Token is not used

**Failure Information**
Authentication does not work, it prompts for user and password.

**Steps to Reproduce**

Set rubrik_cdm_token environment variable and connect to a cluster with rbkcli.

**Context**

**Failure Logs**

PS> set rubrik_cdm_token=mytoken
PS > rbkcli cluster me
Rubrik server IP: a.b.c.d
EnvironmentHandler # No cached API found for this target, importing APIs...
Rubrik username: admin
Rubrik password:

**Comment by keilma** [comment]
When Using Set-Variable it does also not work. When using "set" the variable is added wrong:

```
PS> Get-Variable r*

Name                           Value
----                           -----
rubrik_cdm_token=mytoken...
```


When using Set-Variable it's correct, but rbkcli still prompts for a user and password:

```
PS> Get-Variable r*

Name                           Value
----                           -----
rubrik_cdm_token               mytoken...
rubrik_cdm_token=mytoken...

PS> rbkcli cluster me
Rubrik server IP: a.b.c.d
Rubrik username:
```

Same when using cmd:

```
C:\WINDOWS\system32>set rubrik_cdm_token=mytoken

C:\WINDOWS\system32>rbkcli cluster me
Rubrik server IP: a.b.c.d
Rubrik username:
UserError # Operation Aborted!
```

**Comment by Bmanesco** [comment]
Hello Keilma, 

  Thank you very much for raising this issue.

  Following is my first analysis:

# Symptom:
- When an API token is set it should be used for authentication

# Details:
- When Using Set-Variable it does also not work. When using "set" the variable is added wrong.

# Actions Taken:
### 1st - Env var assignment issue:
- Investigated the difference between the Environmental Variable which Python accesses, Windows cmd Prompt accesses and PowerShell accesses.
- Noticed that Set-Variable and Get-Variable do not change Windows cmd prompt environmental variables.
- In order to get the Windows Environmental Variables the following needs to be performed in PowerShell:
```
PS C:\> Get-ChildItem -Path Env:\

Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
...
rubrik_cdm_node_ip             <IP>
rubrik_cdm_password            <pass>
rubrik_cdm_username            <username>
rubrik_cdm_token               <token>
...
```

- In order to change or assign a new value, the  following needs to be performed in PowerShell:
```
PS C:\> $env:rubrik_cdm_token = <new_token>
PS C:\> Get-ChildItem -Path Env:\

Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
...
rubrik_cdm_token               <new_token>
...
```

### 2nd - Required vars to **rbkcli** authenticate without interaction:
- The required vars for authentication, such as defined in the [quick start](https://github.com/rubrikinc/rbkcli/blob/python27/docs/quick-start.md) documentation, are:
```
rubrik_cdm_node_ip=<IP>
rubrik_cdm_username=<username>
rubrik_cdm_password=<password>
```

- In case you want to use token, additionally you can add the token env var, which will take precedence.

# Conclusion:
- Effectively, if you define a valid IP ('192.168.1.2'), a **invalid** username ('a'), a **invalid** password ('a') and a valid token, the authentication will succeed. **rbkcli** will ignore the provided username and password and use the token for authentication.
- Even though username and password are not used in the authentication with token, they are required to be defined because of other features provided by **rbkcli** such as re-authentication, or ssh redirection, which will be there in the future. 

# Next Steps:
- Please run the following commands in your PowerShell replacing the necessary values:
```
PS C:\> $env:rubrik_cdm_node_ip = '<rubrik_ip>'
PS C:\> $env:rubrik_cdm_userame = 'a'
PS C:\> $env:rubrik_cdm_password = 'a'
PS C:\> $env:rubrik_cdm_token = '<new_token>'
```

- You can now try and run:
```
PS C:\> rbkcli cluster me
```
P.S.: While using **invalid** username and password, whenever the token expires, you will have to manually get a new one from the GUI or provide valid username and password and run:

```
PS C:\> rbkcli session -v v1 -m post
{
  "id": "<id>",
  "organizationId": "<organizationId>",
  "userId": "<userId>",
  "token": "<token>",
  "expiration": "<expiration_date>",
  "tag": "WEB"
}
```

**Comment by keilma** [comment]
Hi Bmanesco, 

I'm still not able to get this running:

```
PS> Get-ChildItem -Path Env:\rubrik*

Name                           Value
----                           -----
rubrik_cdm_username            a
rubrik_cmd_node_ip             a.b.c.d
rubrik_cdm_password            a
rubrik_cmd_token               mytoken...


PS C:\Users\mkeil.SVA> rbkcli cluster me
Rubrik server IP: a.b.c.d
Rubrik username: a
Rubrik password:
ApiRequester # The supplied authentication is invalid
```

**Comment by Bmanesco** [comment]
Thank you Marcel for your report, I am closing this issue.
